apiVersion: bindings.mattmoor.dev/v1alpha1
kind: SinkBinding
metadata:
  name: bind-deploy
spec:
  target:
    apiVersion: apps/v1
    kind: Deployment
    name: debug

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sockeye
---
# kubectl run debug --image=gcr.io/mattmoor-knative/curl sleep 3600
# curl -X POST -H "Content-Type: application/json"  -H "ce-specversion: 1.0"  -H "ce-source: curl-command"  -H "ce-type: curl.demo"  -H "ce-id: 123-abc"  -d '{"name":"I am a Deployment"}' $SINK
