apiVersion: bindings.mattmoor.dev/v1alpha1
kind: SinkBinding
metadata:
  name: test
spec:
  # K8s deployment
  # target:
  #   apiVersion: apps/v1
  #   kind: Deployment
  #   name: debug

  # Knative Service
  target:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: runtime

  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: sockeye
